import images from '../assets/images'

const productsService = [
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Highlight',
        title: 'Trà Xanh Espresso Marble',
        price: 49,
        img: images.prod_1,
        thumb: images.prod_1_thumb,
        path: '/tra-xanh-espresso-marble',
        size: ['Vừa', 'Lớn'],
        topping: ['Sốt Caramel', 'Sốt Espresso', 'Trân Châu Trắng'],
        desc: 'Cho ngày thêm tươi, tỉnh, êm, mượt với Trà Xanh Espresso Marble. Đây là sự mai mối bất ngờ giữa trà xanh Tây Bắc vị mộc và cà phê Arabica Đà Lạt. Muốn ngày thêm chút highlight, nhớ tìm đến sự bất ngờ này bạn nhé!'
    },
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Việt Nam',
        title: 'Cà Phê Sữa Hạnh Nhân Kem Cheese',
        price: 59,
        img: '',
        thumb: images.prod_2_thumb,
        path: '/ca-phe-sua-hanh-nhan-kem-cheese',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Việt Nam',
        title: 'Bạc Xỉu Lắc Sữa Yến Mạch',
        price: 45,
        img: '',
        thumb: images.prod_3_thumb,
        path: '/bac-xiu-lac-sua-yen-mach',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Việt Nam',
        title: 'Bạc Xỉu Lắc Caramel Muối',
        price: 45,
        img: '',
        thumb: images.prod_4_thumb,
        path: '/bac-xiu-lac-caramel-muoi',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Việt Nam',
        title: 'Bạc Xỉu Lắc Hạnh Nhân Nướng',
        price: 45,
        img: '',
        thumb: images.prod_5_thumb,
        path: '/bac-xiu-lac-hanh-nhan-nuong',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Việt Nam',
        title: 'Bơ Arabica',
        price: 45,
        img: '',
        thumb: images.prod_6_thumb,
        path: '/bo-arabica',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Máy',
        title: 'Đường Đen Marble Latte',
        price: 55,
        img: '',
        thumb: images.prod_7_thumb,
        path: '/duong-den-marble-latte',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Máy',
        title: 'Caramel Macchiato Đá',
        price: 55,
        img: '',
        thumb: images.prod_8_thumb,
        path: '/caramel-macchiato-da',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Máy',
        title: 'Caramel Macchiato Nóng',
        price: 55,
        img: '',
        thumb: images.prod_9_thumb,
        path: '/caramel-macchiato-nong',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Máy',
        title: 'Latte Đá',
        price: 55,
        img: '',
        thumb: images.prod_10_thumb,
        path: '/latte-da',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cà Phê Máy',
        title: 'Latte Nóng',
        price: 55,
        img: '',
        thumb: images.prod_11_thumb,
        path: '/latte-nong',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cold Brew',
        title: 'Cold Brew Kim Quất',
        price: 45,
        img: '',
        thumb: images.prod_12_thumb,
        path: '/cold-brew-kim-quat',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cold Brew',
        title: 'Cold Brew Sữa Tươi',
        price: 45,
        img: '',
        thumb: images.prod_13_thumb,
        path: '/cold-brew-sua-tuoi',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Cà Phê',
        type: 'Cold Brew',
        title: 'Cold Brew Truyền Thống',
        price: 45,
        img: '',
        thumb: images.prod_14_thumb,
        path: '/cold-brew-truyen-thong',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trái Cây Xay 0°C',
        type: 'Trái Cây Xay 0°C',
        title: 'Bơ Sữa Phô Mai Tươi',
        price: 55,
        img: '',
        thumb: images.prod_15_thumb,
        path: '/bo-sua-pho-mai-tuoi',
        size: [],
        topping: [],
        desc: '',
        inHome: true
    },
    {
        cate: 'Trái Cây Xay 0°C',
        type: 'Trái Cây Xay 0°C',
        title: 'Dâu Phô Mai Tươi',
        price: 55,
        img: '',
        thumb: images.prod_16_thumb,
        path: '/dau-pho-mai-tuoi',
        size: [],
        topping: [],
        desc: '',
        inHome: true
    },
    {
        cate: 'Trái Cây Xay 0°C',
        type: 'Trái Cây Xay 0°C',
        title: 'Mận Phô Mai Tươi',
        price: 55,
        img: '',
        thumb: images.prod_17_thumb,
        path: '/man-pho-mai-tuoi',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trái Cây Xay 0°C',
        type: 'Trái Cây Xay 0°C',
        title: 'Mãng Cầu Phô Mai Tươi',
        price: 55,
        img: '',
        thumb: images.prod_18_thumb,
        path: '/mang-cau-pho-mai-tuoi',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trái Cây Xay 0°C',
        type: 'Trái Cây Xay 0°C',
        title: 'Nho Phô Mai Tươi',
        price: 55,
        img: '',
        thumb: images.prod_19_thumb,
        path: '/nho-pho-mai-tuoi',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Trái Cây - HiTea',
        type: 'Trà Trái Cây',
        title: 'Oolong Tứ Quý Dâu Trân Châu',
        price: 49,
        img: '',
        thumb: images.prod_20_thumb,
        path: '/oolong-tu-quy-dau-tran-chau',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Trái Cây - HiTea',
        type: 'Trà Trái Cây',
        title: 'Oolong Tứ Quý Kim Quất Trân Châu',
        price: 49,
        img: '',
        thumb: images.prod_21_thumb,
        path: '/oolong-tu-quy-kim-quat-tran-chau',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Trái Cây - HiTea',
        type: 'Trà Trái Cây',
        title: 'Oolong Tứ Quý Vải',
        price: 49,
        img: '',
        thumb: images.prod_22_thumb,
        path: '/oolong-tu-quy-vai',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Trái Cây - HiTea',
        type: 'Trà Trái Cây',
        title: 'Trà Đào Cam Sả - Đá',
        price: 49,
        img: '',
        thumb: images.prod_23_thumb,
        path: '/tra-dao-cam-sa-da',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Trái Cây - HiTea',
        type: 'Trà Trái Cây',
        title: 'Oolong Tứ Quý Sen',
        price: 49,
        img: '',
        thumb: images.prod_24_thumb,
        path: '/oolong-tu-quy-sen',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Trái Cây - HiTea',
        type: 'Hi-Tea',
        title: 'Hi-Tea Đào Kombucha',
        price: 59,
        img: '',
        thumb: images.prod_25_thumb,
        path: '/hi-tea-dao-kombucha',
        size: [],
        topping: [],
        desc: '',
        inHome: true
    },
    {
        cate: 'Trà Trái Cây - HiTea',
        type: 'Trà Trái Cây',
        title: 'Hi-Tea Yuzu Kombucha',
        price: 59,
        img: '',
        thumb: images.prod_26_thumb,
        path: '/hi-tea-yuzu-kombucha',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Trái Cây - HiTea',
        type: 'Trà Trái Cây',
        title: 'Hi-Tea Yuzu Trân Châu',
        price: 49,
        img: '',
        thumb: images.prod_27_thumb,
        path: '/hi-tea-yuzu-tran-chau',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Trái Cây - HiTea',
        type: 'Trà Trái Cây',
        title: 'Hi-Tea Vải',
        price: 49,
        img: '',
        thumb: images.prod_28_thumb,
        path: '/hi-tea-vai',
        size: [],
        topping: [],
        desc: '',
        inHome: true
    },
    {
        cate: 'Trà Sữa',
        type: 'Trà Sữa',
        title: 'Oolong Sữa Hạnh Nhân (Nóng)',
        price: 55,
        img: '',
        thumb: images.prod_29_thumb,
        path: '/oolong-sua-hanh-nhan-nong',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Sữa',
        type: 'Trà Sữa',
        title: 'Oolong Sữa Hạnh Nhân Trân Châu Hoàng Kim',
        price: 59,
        img: '',
        thumb: images.prod_30_thumb,
        path: '/oolong-sua-hanh-nhan-tran-chau-hoang-kim',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Sữa',
        type: 'Trà Sữa',
        title: 'Trà Sữa Oolong Tứ Quý Sương Sáo',
        price: 55,
        img: '',
        thumb: images.prod_31_thumb,
        path: '/tra-sua-oolong-tu-quy-suong-sao-1',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Sữa',
        type: 'Trà Sữa',
        title: 'Trà Sữa Oolong BLao',
        price: 39,
        img: '',
        thumb: images.prod_32_thumb,
        path: '/tra-sua-oolong-blao-2',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Sữa',
        type: 'Trà Sữa',
        title: 'Trà Sữa Oolong Tứ Quý Bơ',
        price: 59,
        img: '',
        thumb: images.prod_33_thumb,
        path: '/tra-sua-oolong-tu-quy-bo',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Sữa',
        type: 'Trà Sữa',
        title: 'Trà Sữa Oolong Nướng Sương Sáo',
        price: 55,
        img: '',
        thumb: images.prod_34_thumb,
        path: '/tra-sua-oolong-nuong-suong-sao',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Xanh - Chocolate',
        type: 'Trà Xanh Tây Bắc',
        title: 'Trà Xanh Latte Sữa Hạnh Nhân (Nóng)',
        price: 55,
        img: '',
        thumb: images.prod_35_thumb,
        path: '/tra-xanh-latte-sua-hanh-nhan-nong',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Xanh - Chocolate',
        type: 'Trà Xanh Tây Bắc',
        title: 'Trà Xanh Latte Sữa Hạnh Nhân',
        price: 59,
        img: '',
        thumb: images.prod_36_thumb,
        path: '/tra-xanh-latte-sua-hanh-nhan',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Xanh - Chocolate',
        type: 'Trà Xanh Tây Bắc',
        title: 'Trà Xanh Espresso Marble',
        price: 49,
        img: '',
        thumb: images.prod_37_thumb,
        path: '/tra-xanh-espresso-marble',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Xanh - Chocolate',
        type: 'Trà Xanh Tây Bắc',
        title: 'Trà Xanh Latte Sữa Yến Mạch',
        price: 55,
        img: '',
        thumb: images.prod_38_thumb,
        path: '/tra-xanh-latte-sua-yen-mach',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Xanh - Chocolate',
        type: 'Trà Xanh Tây Bắc',
        title: 'Trà Xanh Latte Đậm Vị',
        price: 49,
        img: '',
        thumb: images.prod_39_thumb,
        path: '/tra-xanh-latte-dam-vi',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Xanh - Chocolate',
        type: 'Trà Xanh Tây Bắc',
        title: 'Trà Xanh Latte',
        price: 45,
        img: '',
        thumb: images.prod_40_thumb,
        path: '/tra-xanh-latte-1',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Xanh - Chocolate',
        type: 'Trà Xanh Tây Bắc',
        title: 'Trà Xanh Latte Sữa Yến Mạch (Nóng)',
        price: 55,
        img: '',
        thumb: images.prod_41_thumb,
        path: '/tra-xanh-latte-sua-yen-mach-nong',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Xanh - Chocolate',
        type: 'Chocolate',
        title: 'Choco Sữa Hạnh Nhân Kem Cheese',
        price: 59,
        img: '',
        thumb: images.prod_42_thumb,
        path: '/choco-sua-hanh-nhan-kem-cheese',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Xanh - Chocolate',
        type: 'Chocolate',
        title: 'Chocolate Đá',
        price: 55,
        img: '',
        thumb: images.prod_43_thumb,
        path: '/chocolate-da',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Trà Xanh - Chocolate',
        type: 'Chocolate',
        title: 'Chocolate Nóng',
        price: 55,
        img: '',
        thumb: images.prod_44_thumb,
        path: '/chocolate-nong',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Thức uống đá xay',
        type: 'Đá xay Frosty',
        title: 'Frosty Phin-Gato',
        price: 55,
        img: '',
        thumb: images.prod_45_thumb,
        path: '/frosty-phin-gato',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Thức uống đá xay',
        type: 'Đá xay Frosty',
        title: 'Frosty Bánh Kem Dâu',
        price: 59,
        img: '',
        thumb: images.prod_46_thumb,
        path: '/frosty-banh-kem-dau',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Bánh & Snack',
        type: 'Bánh mặn',
        title: 'Bánh Mì Que Chà Bông Phô Mai Bơ Cay',
        price: 22,
        img: '',
        thumb: images.prod_47_thumb,
        path: '/banh-mi-que-cha-bong-pho-mai-bo-cay',
        size: [],
        topping: [],
        desc: '',
        inHome: true
    },
    {
        cate: 'Bánh & Snack',
        type: 'Bánh mặn',
        title: 'Bánh Mì Que Pate',
        price: 15,
        img: '',
        thumb: images.prod_48_thumb,
        path: '/banh-mi-que-pate',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Bánh & Snack',
        type: 'Bánh mặn',
        title: 'Bánh Mì Que Pate Cay',
        price: 15,
        img: '',
        thumb: images.prod_49_thumb,
        path: '/banh-mi-que-pate-cay',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Bánh & Snack',
        type: 'Bánh mặn',
        title: 'Croissant trứng muối',
        price: 39,
        img: '',
        thumb: images.prod_50_thumb,
        path: '/croissant-trung-muoi',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Bánh & Snack',
        type: 'Bánh ngọt',
        title: 'Mochi Kem Trà Sữa Trân Châu',
        price: 19,
        img: '',
        thumb: images.prod_51_thumb,
        path: '/mochi-kem-tra-sua-tran-chau',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Bánh & Snack',
        type: 'Bánh ngọt',
        title: 'Mochi Kem Phúc Bồn Tử',
        price: 19,
        img: '',
        thumb: images.prod_52_thumb,
        path: '/mochi-kem-phuc-bon-tu',
        size: [],
        topping: [],
        desc: '',
        inHome: true
    },
    {
        cate: 'Bánh & Snack',
        type: 'Bánh ngọt',
        title: 'Mochi Kem Việt Quất',
        price: 19,
        img: '',
        thumb: images.prod_53_thumb,
        path: '/mochi-kem-viet-quat',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Bánh & Snack',
        type: 'Bánh Pastry',
        title: 'Butter Croissant',
        price: 29,
        img: '',
        thumb: images.prod_54_thumb,
        path: '/butter-croissant',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Bánh & Snack',
        type: 'Bánh Pastry',
        title: 'Choco Croffle',
        price: 39,
        img: '',
        thumb: images.prod_55_thumb,
        path: '/choco-croffle',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Thưởng Thức Tại Nhà',
        type: 'Cà phê tại nhà',
        title: 'Cà Phê Đen Đá Túi (30 gói x 16g)',
        price: 116,
        img: '',
        thumb: images.prod_56_thumb,
        path: '/ca-phe-den-da-tui-30-goi-x-16g',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Thưởng Thức Tại Nhà',
        type: 'Cà phê tại nhà',
        title: 'Cà Phê Đen Đá Hộp (14 gói x 16g)',
        price: 66,
        img: '',
        thumb: images.prod_57_thumb,
        path: '/ca-phe-den-da-hop-14-goi-x-16g',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Thưởng Thức Tại Nhà',
        type: 'Cà phê tại nhà',
        title: 'Cà Phê Sữa Đá Hòa Tan Túi 25x22G',
        price: 127,
        img: '',
        thumb: images.prod_58_thumb,
        path: '/ca-phe-sua-da-hoa-tan-tui-25x22g-1',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Thưởng Thức Tại Nhà',
        type: 'Cà phê tại nhà',
        title: 'Cà Phê Sữa Đá Hòa Tan (10 gói x 22g)',
        price: 53,
        img: '',
        thumb: images.prod_59_thumb,
        path: '/ca-phe-sua-da-hoa-tan-10-goi-x-22g-1',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Thưởng Thức Tại Nhà',
        type: 'Cà phê tại nhà',
        title: 'Cà Phê Rang Xay Original 1 250G',
        price: 82,
        img: '',
        thumb: images.prod_60_thumb,
        path: '/ca-phe-rang-xay-original-1-250g-1',
        size: [],
        topping: [],
        desc: ''
    },
    {
        cate: 'Thưởng Thức Tại Nhà',
        type: 'Cà phê tại nhà',
        title: 'Cà Phê Hoà Tan Đậm Vị Việt (18 gói x 16 gam)',
        price: 55,
        img: '',
        thumb: images.prod_61_thumb,
        path: '/ca-phe-hoa-tan-dam-vi-viet-18-goi-x-16-gam',
        size: [],
        topping: [],
        desc: ''
    }
]

export default productsService
