export { default as Home } from './Home'
export { default as Products } from './Products'
export { default as Collections } from './Collections'
export { default as Pages } from './Pages'
export { default as Blogs } from './Blogs'
export { default as Login } from './Login'
export { default as CartDetail } from './CartDetail'
export { default as Profile } from './Profile'
