export { default as Home } from './Home'
export { default as Products } from './Products'
export { default as Collections } from './Collections'
export { default as Pages } from './Pages'
export { default as Blogs } from './Blogs'
